Feature/32880 precision
wirenboard/wb-mqtt-db pull request #12
Opened 2021-07-21 12:33 UTC by KraPete

* Округление согласно /meta/precision. Если его нет, и в значении число, то запоминаем максимальное число знаков после запятой и округляем до него.
* Если в интервале было одно изменение, то пишем время изменения, а не время интервала.

2021-07-21 13:09 UTC, evgeny-boger requested changes
мне казалось, что там знаки в основном возникают после запроса с агрегацией средствами БД. Оно здесь применяет precision к тем результатам?

2021-07-22 07:32 UTC, KraPete commented
@evgeny-boger  Пропустил это место. Убрал округление из записи в базу и добавил в RPC.

2021-07-22 09:52 UTC, webconn approved these changes

2021-07-22 09:54 UTC, webconn commented
Кстати, если линтиан тут теперь не ругается, можно в jenkinsfile добавить флаг, чтобы проверка запускалась по умолчанию:

```
buildDebSbuild defaultTargets: 'wb6',
               defaultRunLintian: true
```

2021-07-26 05:52 UTC, KraPete commented
@evgeny-boger Вливаем?

2021-07-26 12:01 UTC, evgeny-boger approved these changes

2021-07-26 12:24 UTC, merged