Feature/37814 burst
wirenboard/wb-mqtt-db pull request #15
Opened 2021-07-30 05:16 UTC by KraPete

* Сделал рефакторинг кода. Разнёс классы по отдельным файлам. Вынес логику обработки сообщений от MQTT в отдельный класс. Отвязал его тесты от брокера. Теперь они проходят быстрее, и проще тестировать.
* Добавил max_burst в настройки. Оно определяет максимальное число внеочередных записей. Внеочередная запись добавляется за каждый промежуток, равный min_interval (минимальный интервал записи). Как только приходят новые сообщения, они начинают записываться вне очереди, пока не исчерпан этот накопленный лимит.
* Переделал схему для редактирования настроек. Сделал вкладки вместо списка, убрал ненужные кнопки и поля.

2021-08-02 10:49 UTC, webconn requested changes

2021-08-02 10:49 UTC, webconn commented on README.md
> +      // без учёта минимального периода записи.
Описание что-то непонятное получилось, я не вдуплил.

Может, здесь пример какой-нибудь накидать? Например, что это полезно для записи состояния выключателей в комнатах. И специально указать, что это работает, когда значения вообще меняются редко, но могут приходить частые изменения за небольшой отрезок времени.

2021-08-02 10:49 UTC, webconn commented on config.json
> +            "max_burst": 0
А если мы это сделаем по умолчанию 5 или как-то так, у нас что-то сломается?

2021-08-02 10:49 UTC, webconn commented on dblogger.cpp
> +            if (!event.RawValue.empty()) {
А почему мы теперь не хотим регистрировать пустые значения?

2021-08-02 10:49 UTC, webconn commented on dblogger.cpp
> +    bool MatchPattern(const TChannelName& pattern, const TChannelName& channelName)
Всё-таки в коммит с логикой просочились изменения, к ней явно не относящиеся.
Лучше так не делать

2021-08-02 10:49 UTC, webconn commented on dblogger.cpp
> +            //TODO: fix
а что тут сломано?

2021-08-02 10:49 UTC, webconn commented on dblogger.cpp
> +                --channelData.BurstRecords;
Проверь меня, правильно ли я понял логику:

Если у нас есть ещё квота на запись значений без усреднения, то мы их сразу запихиваем в базу данных, как только они обновились. Как только квота заканчивается (если в реально наблюдаемом выбросе сообщений больше, чем в квоте), то все следующие сообщения осядут где-то в аккумуляторе и запишутся позже. Квота обновится в тот момент, когда будет сессия записи из аккумуляторов.

Всё так?

2021-08-03 09:46 UTC, KraPete commented on config.json
> +            "max_burst": 0
Думаю, ничего не сломается. Хотели вообще переделывать конфиг по умолчанию, можно отдельной задачей сделать.

2021-08-03 09:46 UTC, KraPete commented on dblogger.cpp
> +            if (!event.RawValue.empty()) {
Никогда не регистрировали. Если найти применение, можно добавить

2021-08-03 09:51 UTC, KraPete commented on dblogger.cpp
> +            //TODO: fix
Надо retained корректно проставить. Правда, теперь это невозможно, т.к. событие изменения состояния контрола не несёт информации о retained.
Вообще не ясно, кто-то этим retained в истории пользуется? homeui точно нет.

2021-08-03 09:52 UTC, KraPete commented on dblogger.cpp
> +                --channelData.BurstRecords;
Да

2021-08-03 10:02 UTC, webconn commented on config.json
> +            "max_burst": 0
Ну будет странно сделать такую полезную фичу и не включить её по умолчанию

2021-08-03 10:03 UTC, KraPete commented on dblogger.cpp
> +    bool MatchPattern(const TChannelName& pattern, const TChannelName& channelName)
Очень субъективно. После того, как поменял логику, стало ясно, что тут удобнее структуру передавать, которая используется в логике. 
Выносить 3 строчки в отдельный коммит? Тогда таких изменений можно ещё с десяток набрать.

2021-08-03 10:06 UTC, webconn commented on dblogger.cpp
> +            if (!event.RawValue.empty()) {
А, всё, нашёл соответствующий if в другом месте

2021-08-03 10:09 UTC, webconn commented on dblogger.cpp
> +            //TODO: fix
Ну да, непохоже, что кому-то у нас сейчас это интересно. Наверное, можно даже когда-нибудь удалить это поле отсюда. Короче, стоит уточнить это в комментарии, раз так

2021-08-03 10:17 UTC, KraPete commented on config.json
> +            "max_burst": 0
Тогда надо какое-то значение выбрать. Я чё-то не могу придумать, чем 5 лучше 10, а 10 - 15-и :)

2021-08-03 10:32 UTC, KraPete commented on README.md
> +      // без учёта минимального периода записи.
Добавил в README больше объяснений.

2021-08-03 13:06 UTC, webconn commented on config.json
> +            "max_burst": 0
Я почему-то думаю в сторону значения 20 или 30, как будто это реалистичное количество нажатий кнопки для двух минут отладки (100 - очень много, 10 - реально, но может не хватить).

И, если это не супер-сложно, хочу предложить по умолчанию для контролов с нечисловым значением давать `max_burst` "в кредит" при запуске wb-mqtt-db, чтобы на только что перезапущенном контроллере пользователь мог потыкать в кнопку во время отладки и у него была бы красивая история. Для числовых контролов это в принципе не так уж нужно.

2021-08-04 15:12 UTC, webconn commented on dblogger.cpp
> +        const std::array<const char*, 4> types = {"switch", "alarm", "wo-switch", "pushbutton"};
Думаю, `text` тоже можно сюда сразу (ожидаю какие-нибудь enum-ы тут, может, за редким исключением).
А вообще это ужасно, что у нас наружу не выходит функция, которая говорит про тип данных (т.е. может сказать, что `temperature` - это `value`). Можно даже `TODO` здесь оставить на этот счёт, чтобы сделать здесь проверку "от противного" потом.

2021-08-04 15:15 UTC, KraPete commented on dblogger.cpp
> +        const std::array<const char*, 4> types = {"switch", "alarm", "wo-switch", "pushbutton"};
Низя `text`, оно у нас по умолчанию во всех регистрах modbus ставится, если ничего другого не прописано в шаблоне или настройках. Я ж PR про это делал, вы с Женей тогда разошлись в мнениях, потому пока и не влито.

2021-08-04 15:21 UTC, webconn commented on dblogger.cpp
> +        const std::array<const char*, 4> types = {"switch", "alarm", "wo-switch", "pushbutton"};
Жалко. Давай тогда пока так оставим, но я сделаю таску, чтобы мы подумали об этом ещё. А то ну правда хочется, чтобы енумы могли тоже бёрстить.

2021-08-04 15:22 UTC, webconn approved these changes

2021-08-25 10:19 UTC, KraPete commented
Rebase https://github.com/wirenboard/wb-mqtt-db/pull/18

2021-08-25 10:19 UTC, closed without merging