New averaging logic in RPC.
wirenboard/wb-mqtt-db pull request #27
Opened 2022-05-20 06:50 UTC by KraPete

The service averages values in RPC response if too many records are requested. Otherwise it sends original values even if min_interval is defined in request.

2022-05-20 10:52 UTC, webconn commented
Тут тесты попадали

2022-05-20 13:47 UTC, KraPete commented
> Тут тесты попадали

Починил

2022-05-24 11:44 UTC, webconn commented on sqlite_storage.cpp
> +    int maxNotAveragedRecords = (((endTime - startTime) / minInterval) * 1.1);
Вот я всё-таки по-другому хотел бы решить задачу.

Думаю, что то, что есть здесь, есть смысл оставить для совместимости и не трогать больше, пока не попросят (например, у нас можно делать запросы через cli, или кто-то пишет усреднения в облако, вдруг кому понадобится). Можно и deprecated потом будет навесить на этот метод.

Я скорее за то, чтобы сделать новый RPC-запрос, в котором количество запрашиваемых точек можно было бы ограничить явным образом. Это будет более понятная сущность и для homeui (которому ограничивать количество точек надо, чтобы регулировать объём трафика и сложность отрисовки), и для бэкенда (не надо делать волшебных пересчётов с умножением на 1.1).

Бонусом я бы сделал запрос количества доступных точек отдельно, чтобы интерфейс по 10 минут не загружал историю канала, которая пуста (я про это тикет делал). Если это станет узким местом в запросе истории, можно было бы даже кешировать примерное количество точек по каждому каналу в базе (хотя бы порядок).

2022-05-25 05:39 UTC, KraPete commented on sqlite_storage.cpp
> +    int maxNotAveragedRecords = (((endTime - startTime) / minInterval) * 1.1);
1. Количество запрашиваемых точек это длина интервала, делённая на минимальный интервал между точками. Это всё и так в запросе приходит, если надо.
2. Не понимаю зачем надо запрашивать число доступных точек? Что потом с ним делать?
3. По 10 минут первый раз слышу. Сервис возвращает пустой ответ в таком случае. Если что-то где-то тормозит, то скорее надо смотреть логику запроса со стороны web-интерфейса. Сейчас в запросе всё есть: гарницы интервала, минимальный интервал для усреднения, id точки внутри интервала, с которой надо начинать отдавать данные.

2022-05-25 07:37 UTC, webconn commented on sqlite_storage.cpp
> +    int maxNotAveragedRecords = (((endTime - startTime) / minInterval) * 1.1);
1. Ну это всё равно магия, а в коде она вот ещё сопровождается умножением на 1.1. Более того, раньше получалось, что запрос с минимальным интервалом давал заведомо разреженную последовательность точек, а теперь вдруг перестал.
2. Пока не придумал, можно и не делать.
3. Я так и не написал багрепорт про это. Суть в том, что если выбрать большой период, homeui заранее разбивает запрос на несколько небольших (не зная, что у бэкенда ничего нет), и начинает их методично отправлять, получая пустые ответы. Про 10 минут я утрировал, конечно, это в сумме может занимать около полуминуты на не очень уверенном соединении, но поведение странное и неочевидное.

2022-05-25 08:01 UTC, KraPete commented on sqlite_storage.cpp
> +    int maxNotAveragedRecords = (((endTime - startTime) / minInterval) * 1.1);
1. Могу не умножать, не знаю зачем сделал, сейчас не могу найти логического объяснения. 
Мы же как раз с излишним усреднением боремся. Если точек будет отправлено всё равно столько же, а точность выше, то в чём проблема?

2022-06-23 12:44 UTC, webconn commented on sqlite_storage.cpp
> +    int maxNotAveragedRecords = (((endTime - startTime) / minInterval) * 1.1);
Я полистал интернеты в поисках аргументации для себя, и вот что нашёл:

https://grafana.com/docs/grafana/latest/panels/query-options/
Grafana, например, в настройках запроса не предлагает минимальный интервал в том смысле, который есть у нас, зато предлагает максимальное количество точек, которое (сюрприз!) определяется шириной панели в пикселях.

Мне это API нравится, потому что немного унифицирует нас с той же grafana (если вдруг кому-то понадобится пользоваться этим API в принципе), к тому же сразу становится понятно, как считать параметры запроса. Ещё плюс - не надо заниматься всякими оценками на стороне клиента, прикидывать интервал усреднения от размера запрашиваемого периода и от размера экрана, например. 

То API, которое у нас сейчас есть, возможно, кому-то нужно (в смысле дизайна запроса), но это не точно.

У API, которое здесь получилось, есть ещё один коварный аспект. Если мы работаем с разреженными данными, которые за период (условно 1 час) активно менялись в течение 10 минут, есть риск внезапно получить очень резкое усреднение в зависимости от реального количества точек. Условно, было в куче 100 точек - не усредняем, а стало 101 - начали усреднять, да ещё и заранее заданным фиксированным окном (читай - достаточно большим для этой плотности).

Понятно, что на стороне бэкенда будут приколы для того, чтобы такое усреднение заработало как надо, но думаю, оно того будет стоить.

Реализовать можно не как отдельный RPC-запрос, а просто добавив параметр в этот, и игнорировать min_interval, если новый параметр задан.

2022-06-23 20:42 UTC, evgeny-boger commented on sqlite_storage.cpp
> +    int maxNotAveragedRecords = (((endTime - startTime) / minInterval) * 1.1);
так по-моему если задача - не рисовать больше точек, чем пикселей в дисплее, то надо как раз интервал (между пикселями) задавать, а не общее количество. Как раз из-за того, что данные могут быть разреженые.

Графана - ну там вообще-то тоже самая стандартная штука - это GROUP BY $interval. Т.е. от масштабе меняется интервал, а не общее количество точек.

2022-06-24 09:15 UTC, webconn commented on sqlite_storage.cpp
> +    int maxNotAveragedRecords = (((endTime - startTime) / minInterval) * 1.1);
Да, но фиксированный интервал, посчитанный на фронтенде, резко нас ограничивает в том, чтобы за один раз загрузить больше данных, если реально точек мало. То есть, агрессивно укладывать данные в количество пикселей мы должны только в случае, когда их реально много, а если их мало, то почему бы сразу все не получить

2022-07-06 05:14 UTC, KraPete commented on sqlite_storage.cpp
> +    int maxNotAveragedRecords = (((endTime - startTime) / minInterval) * 1.1);
Я опять потерялся.
Проблемы:
1. Если временной интервал большой, надо запросить у wb-mqtt-db усреднение, чтобы не выкачивать мегабайты точек.
2. Если точек в интервале мало, а мы запросили усреднение, то получим нежелательное сглаживание, т.к. усреднять будем по фиксированным интервалам. Тут хочется получить сырые данные, т.к. их не много.

В запросе есть  параметры (https://github.com/wirenboard/wb-mqtt-db#%D0%B2%D1%85%D0%BE%D0%B4%D0%BD%D1%8B%D0%B5-%D0%BF%D0%B0%D1%80%D0%B0%D0%BC%D0%B5%D1%82%D1%80%D1%8B-1):
- интервал усреднения
- максимальное число точек в ответе

Идея текущего API, видимо, была следующая.
Запрашиваем интервал с усреднением и просим из него N усреднённых точек. Получили, запросили из этого же интервала с тем же усредением следующий кусок. Для этого есть id точки, с которого надо присылать.

Сейчас я делю весь интервал на запрощенный интервал усреднения и получаю число точек, которое может отобразить homeui. Если во всём запрошенном интервале их меньше чем результат деления, то не усредняю, иначе усреденяю.

Можно добавить ещё параметр `желаемое число точек во всём интервале`, как Никита предлагает, который будет иметь приоритет над интервалом усреднения. Если точек во всём интервале меньше, то шлём без усреднения, если больше, то вычисляем интервал усреденения и шлём усреднённые. Тогда старые запросы будут работать как раньше, а в homeui можно будет переделать на запрос с числом точек.

2022-07-06 07:50 UTC, webconn commented on sqlite_storage.cpp
> +    int maxNotAveragedRecords = (((endTime - startTime) / minInterval) * 1.1);
Идея текущего API, кажется, была такой:

1. Запрашиваем интервал с усреднением и говорим, сколько точек за раз мы готовы принять
2. Если точек получилось `<= limit`, то принимаем все, и в ответе нет флага `has_more`.
3. Если точек `> limit`, то получаем `limit` точек и флаг `has_more`, на основании этого делаем ещё запрос, goto 1

Я считаю, что для фронтенда этот механизм порождает много внезапной магии, что надо самому придумывать интервал усреднения (и сейчас это не работает как надо, раз у нас дискретные сигналы постоянно усредняются). (Кстати, и магия по разбивке на чанки по limit работает тоже как попало, для примера можно попробовать запросить данные за месяц из канала, где их столько нет, и получить много запросов с пустыми ответами, но сейчас это оффтопик.)

Если вообще подумать, для чего тут нужно усреднение, есть такие мотивации:

1. Экономия трафика между фронтом и бэком.
2. Экономия места на флешке для базы (но там другая логика усреднения со своими интервалами).
3. Экономия вычислительных ресурсов клиента на отрисовку горы точек.

По-моему, тут даже интуитивно проще оперировать количеством точек, а не интервалом усреднения. Бэкенд в состоянии сходить в базу, прикинуть, сколько у нас точек за период, и из этого решить, как именно их надо усреднять, чтобы ублажить фронтенд. Это тоже порождает магию, но по крайней мере она будет происходить в том месте, где есть больше данных для принятия адекватного решения.

Да, идея с параметром `желаемое число точек в интервале` хорошая, я бы даже заставил его конфликтовать с параметром `интервал усреднения`, чтобы уж наверняка. И заставить фронт пользоваться только новым параметром, не пытаясь на своей стороне додумать за бэкенд, как лучше усреднить.

2022-07-06 15:50 UTC, KraPete commented
@webconn добавил параметр

2022-07-06 16:07 UTC, webconn commented on dblogger.cpp
> +    if (params.isMember("max_records")) {
Я бы подумал, как будут реагировать старые версии wb-mqtt-db без этого параметра на запросы с этим параметром. Всё будет работать хорошо, если писать все параметры сразу, но это оставит кучу страшного кода в одном месте в homeui. А ещё никак нельзя понять удалённо, поддерживает ли эта версия wb-mqtt-db запросы с `max_records`.

Мне кажется, архитектурно более чистое решение - сделать два RPC-эндпоинта, и на стороне homeui принимать решение о том, какой из них использовать (если нет нового - использовать старый)

2022-07-06 16:45 UTC, KraPete commented on dblogger.cpp
> +    if (params.isMember("max_records")) {
Так-то это одна строка тут https://github.com/wirenboard/homeui/blob/4157f21e9e14534c2059dabead0003ea33282fc3/app/scripts/controllers/historyController.js#L451
Но вообще код там, конечно, странный :confused:

2022-07-06 16:49 UTC, evgeny-boger commented on sqlite_storage.cpp
> +    int maxNotAveragedRecords = (((endTime - startTime) / minInterval) * 1.1);
я не понимаю, в чём проблема передавать с фронтенда интервал усреднения.  Ну вот вообще не понимаю.
Интервал = 2 пикселя на графике например.
Графана передаёт, почему мы передавать не можем?

Чанки можно вообще к чёртовой матери выкинуть, если и без них быстро работает.

2022-07-07 08:38 UTC, KraPete commented on sqlite_storage.cpp
> +    int maxNotAveragedRecords = (((endTime - startTime) / minInterval) * 1.1);
@evgeny-boger Вот с чем мы боремся.

Реальные данные:
![изображение](https://user-images.githubusercontent.com/86825564/177729571-d6d16099-d616-4ff1-961e-2da45cd933b4.png)

Изменили временной интервал:
![изображение](https://user-images.githubusercontent.com/86825564/177730031-de934e30-e3b4-4e1a-8945-97e62b717344.png)

Ещё раз изменили временной интервал:
![изображение](https://user-images.githubusercontent.com/86825564/177729796-dc46c658-3e98-45e6-820f-59f7345fb56e.png)

Получили усреднение. Всё из-за того, что homeui во всех запросах присылает интервал усреднения. Мы хотим чтобы усреднение было более избирательным.

2022-07-19 12:20 UTC, webconn commented
Стало лучше, мне уже почти нравится.

Пробовал с этим поиграться, и столкнулся с такой проблемой. Если щёлкать каналом достаточно часто (так, чтобы за одну секунду пару раз нажать - да, это можно сделать мышкой), может получиться, что сообщения будут иметь таймстемпы, совпадающие до секунд (но разные в миллисекундах). Это у нас корректно хранится в базе (в миллисекундах), но когда мы отправляем ответ с данными в виде JSON, там таймстемпы округляются до секунд.

Получается так:

В базе:
![image](https://user-images.githubusercontent.com/1550335/179747946-eb4d4f0e-806f-4fd9-bdd4-c57b3a73f315.png)

В ответе на запрос:
```json
{
  "error": null,
  "id": 17,
  "result": {
    "values": [
      {
        "c": 5,
        "i": 1575389,
        "retain": false,
        "t": 1658231046,
        "v": "0"
      },
      {
        "c": 5,
        "i": 1575390,
        "retain": false,
        "t": 1658231047,
        "v": "1"
      },
      {
        "c": 5,
        "i": 1575391,
        "retain": false,
        "t": 1658231049,
        "v": "0"
      },
      {
        "c": 5,
        "i": 1575392,
        "retain": false,
        "t": 1658231049,
        "v": "1"
      },
      {
        "c": 5,
        "i": 1575393,
        "retain": false,
        "t": 1658231051,
        "v": "0"
      },
      {
        "c": 5,
        "i": 1575394,
        "retain": false,
        "t": 1658231052,
        "v": "1"
      },
      {
        "c": 5,
        "i": 1575395,
        "retain": false,
        "t": 1658231054,
        "v": "0"
      }
    ]
  }
}
```

На странице:
![image](https://user-images.githubusercontent.com/1550335/179748256-56b25f5c-c44d-4e2f-8d49-74bb6e7ff297.png)

В CSV:
```csv
Date and time,"A3 Terminal (Discrete I/O / A3_OUT)"
Jul 19, 2022 2:44:06 PM,0
Jul 19, 2022 2:44:07 PM,1
Jul 19, 2022 2:44:09 PM,0
Jul 19, 2022 2:44:11 PM,0
Jul 19, 2022 2:44:12 PM,1
Jul 19, 2022 2:44:14 PM,0
```

Наверное, решением было бы отправлять таймстемпы как числа с плавающей или фиксированной точкой (с фиксированной кажется лучше, можно миллисекунды даже отдельным полем отправлять, так не сломается совместимость) и разбирать это на фронтенде соответственно.

Как думаешь, насколько сложно это будет сделать? Мне кажется, без этого юзерстори "хочу красивые меандры дискретных сигналов" опять останется недоделанной на чуть-чуть

2022-07-19 12:32 UTC, KraPete commented
@webconn Оно и так не будет доделано, сделай больше 1000 переключений и получишь усреднение снова.
мс тут будут показывать непойми что, т.к. у нас нет в mqtt нормальных временных отметок.
График, кстати, верный, а вот табличка, да, кривая. Надо как в графике сделать.

2022-07-19 12:36 UTC, webconn commented
> @webconn Оно и так не будет доделано, сделай больше 1000 переключений и получишь усреднение снова. мс тут будут показывать непойми что, т.к. у нас нет в mqtt нормальных временных отметок. График, кстати, верный, а вот табличка, да, кривая. Надо как в графике сделать.

Ну 1000 переключений - это не очень реалистично в системе с MQTT в роли транспорта, а вот 2-3 раза в секунду кажется нормальным.

С разницей в 300-500 мс и без особых временных отметок в сообщениях можно работать, я только что привёл пример :)

График не совсем верный, особенно если его бесконечно приближать - там всегда будет иголка, и при наведении мышки он показывает только одно значение (0, вроде как)

2022-07-21 07:30 UTC, KraPete commented
> > @webconn Оно и так не будет доделано, сделай больше 1000 переключений и получишь усреднение снова. мс тут будут показывать непойми что, т.к. у нас нет в mqtt нормальных временных отметок. График, кстати, верный, а вот табличка, да, кривая. Надо как в графике сделать.
> 
> Ну 1000 переключений - это не очень реалистично в системе с MQTT в роли транспорта, а вот 2-3 раза в секунду кажется нормальным.
> 
> С разницей в 300-500 мс и без особых временных отметок в сообщениях можно работать, я только что привёл пример :)
> 
> График не совсем верный, особенно если его бесконечно приближать - там всегда будет иголка, и при наведении мышки он показывает только одно значение (0, вроде как)

Сделал передачу мс как дробную часть.

2022-07-21 18:25 UTC, webconn requested changes
С точки зрения UX результат мне нравится, но есть пара технических вопросов

2022-07-21 18:25 UTC, webconn commented on sqlite_storage.h
> +    void GetRecords(IRecordsVisitor&                      visitor,
Давай уникальные имена для этих методов, а то перегрузка неочевидная и плохо читается

2022-07-21 18:25 UTC, webconn commented on dblogger.cpp
> -    auto minInterval = std::chrono::milliseconds(int64_t(minIntervalMs));
А это точно пора убирать?

2022-07-21 18:25 UTC, webconn commented on dblogger.cpp
> +        row["t"] = duration_cast<milliseconds>(timestamp.time_since_epoch()).count() / 1000.0;
Я немного переживаю, что у каких-нибудь ещё клиентов может быть софт, на это завязанный, и он может окуклиться, если получит float вместо int. Предлагаю в этом месте сделать селектор в запросе, например (типа флаг `with_milliseconds` или `precision="ms"/"s"`)

2022-07-22 05:21 UTC, KraPete commented on dblogger.cpp
> -    auto minInterval = std::chrono::milliseconds(int64_t(minIntervalMs));
Оно вниз переехало, в другую ветку if.

2022-07-22 05:42 UTC, KraPete commented on dblogger.cpp
> +        row["t"] = duration_cast<milliseconds>(timestamp.time_since_epoch()).count() / 1000.0;
Добавил `with_milliseconds`

2022-07-22 05:42 UTC, KraPete commented on sqlite_storage.h
> +    void GetRecords(IRecordsVisitor&                      visitor,
Переименовал

2022-07-22 17:18 UTC, webconn approved these changes

2022-07-25 02:31 UTC, merged